#!/bin/bash
GPG=/usr/bin/gpg
pass=$(gpg --list-keys | tail -3 | head -1 | awk '{print $3}')


$GPG --armor --export-secret-keys ${pass} > ${HOME}/automation/${pass}.key.asc
$GPG --yes --delete-secret-key $pass
echo "La llave secreta ha sido eliminada del (1)anillo de confianza exportada al archivo ${HOME}/automation/secreta.key"
echo "Por favor guardar en un lugar seguro!"

# (1) Anillo de confianza se refiere a los pares de llaves publicas/secretas que estan en la pc local
# Cuand se tiene la clave secreta localmente cualquier persona con el passphrase puede desencritar los
# archivos encriptados, si no esta la llave secreta es imposible desencriptar.
~                                                                                 